// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwpkauB-JmbB7haJsJn13zoQRWZnH3rIk',
    appId: '1:879327846869:web:00fb006851db29d5e6dd5c',
    messagingSenderId: '879327846869',
    projectId: 'mobilpark-e6650',
    authDomain: 'mobilpark-e6650.firebaseapp.com',
    storageBucket: 'mobilpark-e6650.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq-RnMGUhOqJkL-HMHeXIms82JtYGYTNk',
    appId: '1:879327846869:android:610cafa98d154598e6dd5c',
    messagingSenderId: '879327846869',
    projectId: 'mobilpark-e6650',
    storageBucket: 'mobilpark-e6650.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRAqpkujVXYDngxig7Rd3fTqruoTnzjpk',
    appId: '1:879327846869:ios:9d1b9d0d8c4aadb6e6dd5c',
    messagingSenderId: '879327846869',
    projectId: 'mobilpark-e6650',
    storageBucket: 'mobilpark-e6650.firebasestorage.app',
    iosBundleId: 'com.example.mobilPark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRAqpkujVXYDngxig7Rd3fTqruoTnzjpk',
    appId: '1:879327846869:ios:9d1b9d0d8c4aadb6e6dd5c',
    messagingSenderId: '879327846869',
    projectId: 'mobilpark-e6650',
    storageBucket: 'mobilpark-e6650.firebasestorage.app',
    iosBundleId: 'com.example.mobilPark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwpkauB-JmbB7haJsJn13zoQRWZnH3rIk',
    appId: '1:879327846869:web:31bdaf8124a8318de6dd5c',
    messagingSenderId: '879327846869',
    projectId: 'mobilpark-e6650',
    authDomain: 'mobilpark-e6650.firebaseapp.com',
    storageBucket: 'mobilpark-e6650.firebasestorage.app',
  );
}
